import type { Metadata } from "next";
import "./globals.css";
import { headingsFont, copyFont } from "@/assets/fonts";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "font-copy font-medium antialiased",
          `${headingsFont.variable} ${copyFont.variable}`,
        )}
      >
        {children}
      </body>
    </html>
  );
}
